feat: re-use flexible checksums SHA256
awslabs/smithy-kotlin pull request #1018
Opened 2023-12-26 17:06 UTC by lauzadis

If SHA256 is used for flexible checksums, it can also be re-used in the signer to avoid recalculating a body hash.

## Issue \#

Addresses an optimization mentioned in https://github.com/awslabs/aws-sdk-kotlin/issues/1157

## Description of changes

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-12-27 14:30 UTC, aajtodd requested changes
This change seems _ok_ but I don't think it addresses the underlying issue. If a user submits a request without a flexible checksum this would still fail right? I think we need to solve that because it looks like the request in the issue without a checksum should succeed as well unless I'm missing something.

2023-12-27 14:30 UTC, aajtodd commented on runtime/auth/http-auth-aws/common/src/aws/smithy/kotlin/runtime/http/auth/AwsHttpSigner.kt
> +                request.headers["x-amz-checksum-sha256"] != null -> {
**suggestion**: Should probably be a constant value somewhere.

2023-12-27 14:30 UTC, aajtodd commented on runtime/auth/http-auth-aws/common/src/aws/smithy/kotlin/runtime/http/auth/AwsHttpSigner.kt
> +                request.headers["x-amz-checksum-sha256"] != null -> {
**fix**: Needs tests

2023-12-28 20:01 UTC, aajtodd approved these changes

2024-01-02 21:05 UTC, ianbotsf approved these changes

2024-01-02 21:05 UTC, ianbotsf commented on runtime/auth/aws-signing-common/common/src/aws/smithy/kotlin/runtime/auth/awssigning/internal/AwsChunkedUtil.kt
> +        (isOneShot || (contentLength?.compareTo(AWS_CHUNKED_THRESHOLD) ?: 0) > 0)
**Style**: `?.compareTo` works but is pretty verbose and still requires null-coalescing the value. Shorter would just be:

```kotlin
(contentLength ?: 0 > AWS_CHUNKED_THRESHOLD)
```

Same comment applies below.

2024-01-05 15:09 UTC, closed without merging