misc: separate **codegen** version
awslabs/smithy-kotlin pull request #992
Opened 2023-11-07 18:59 UTC by lauzadis

## Issue \#

## Description of changes

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-11-07 23:27 UTC, ianbotsf approved these changes

2023-11-07 23:27 UTC, ianbotsf commented on gradle.properties
> +smithyKotlinCodegenVersion=0.28.2-SNAPSHOT
**Suggestion**: I like the simplicity of `sdkVersion` for the runtime and by comparison `smithyKotlinCodegenVersion` seems wordy and verbose. How about `codegenVersion`?

2023-11-08 14:42 UTC, aajtodd approved these changes

2023-11-08 15:03 UTC, aajtodd requested changes

2023-11-08 15:03 UTC, aajtodd commented on .github/workflows/continuous-integration.yml
> +        sed -i "s/smithy-kotlin-runtime-version = .*$/smithy-kotlin-runtime-version = \"$SMITHY_KOTLIN_VERSION\"/" gradle/libs.versions.toml
You'll need to replace codegen version as well.

2023-11-09 20:21 UTC, merged